version: '3'
services:
  web:
   image: nginx:latest
   ports:
    - "8082:80"
   volumes:
     - ./:/app
     - ./docker/nginx/logs/:/var/log/nginx
     - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
   links:
    - php
  php:
    build:
      context: .
      dockerfile: ./docker/images/Dockerfile-php
    volumes:
    - ./:/app

